### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eM-Krow** [Rehike/Rehike#10]
So in terms of layouts, performance wise, the hitchhiker layout had much better performance compared to polymer/material. Reverting the layout with extensions got back the performance, though those are no longer available. 

Does this project when it restores the layout improve the performance like extensions reverting the layout did? Or is this done in a way where that isn't possible?

**Comment by randomperson189** [comment]
Technically Rehike doesn't have anything to do with the Polymer layout, it's a frontend that basically reconstructs the Hitchhiker layout locally and proxy programs redirect youtube to your local web server. Answering your question, I do notice a performance increase when loading pages

**Comment by YukisCoffee** [comment]
As mentioned in the above comment, Rehike is a completely custom YouTube server that generates pages which are very similar to actual Hitchhiker pages. 

Request time is completely dependent on the PHP runtime and your own specifications, however it should be faster than the download + load time of Polymer combined.

Actual pages should perform just about exactly the same as they would if you were actually using Hitchhiker straight from YouTube's servers, since the HTML, JS, and CSS are hardly any different.

**Comment by eM-Krow** [comment]
Answer is appreciated thanks. It's also glad to hear that it will be basically the same performance, that's the big benefit I liked it over polymer (besides the actual visual layout of it). Will likely use this in the future once it's more developed (and once I can actually figure out how to actually use it in XAMP/Fiddler).
