### ISSUE TITLE
Can Old YouTube Studio be reverted in Rehike?

### ISSUE THREAD

**Issue by coffeemccoffeeeeeee** [Rehike/Rehike#112]

**Comment by aubymori** [comment]
I think it's possible. However, this is the at the very least of our priorities. It would also be very difficult given that the structure of YouTube Studio is very different from that of the old Creator Studio.

**Comment by randomperson189** [comment]
I'm not sure if a Creator Studio revival has been attempted yet but I would like to see one down the line. Maybe when Rehike gets more developed it could be used as a base for an attempt of a Creator Studio frontend.

**Comment by YukisCoffee** [comment]
Indeed, Creator Studio is not directly in the plans and thus won't be implemented in the foreseeable future.

There are a few reasons for not implementing it:
- Actions are protected through attestation using Google's botguard, which is the same technology that powers the backend of reCAPTCHA. This security mechanism makes it extremely difficult to forge a request to the Creator Studio API, which unfortunately, we need to be able to do in order to implement a custom frontend.
- There already exists [an official Creator Studio frontend](//studio.youtube.com) that is separate from Rehike. So use is not impaired by having Rehike installed.
- Rehike's userbase will remain small and Creator Studio is used much less than other parts of YouTube. As such, it will be harder to ensure stability, and limited reward for implementing it.

These plans may change in the future, but for now, the goal is to purely keep Rehike to a general YouTube frontend.
