### ISSUE TITLE
Non shelves mode for WEB V2 is missing

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#120]
It seems that the option to not use shelves for WEB V2 isn't there anymore, you activated it by setting **"useWebV2HomeEndpoint": true** in the config, here's what the layout looks like with the 2 layout options
![image](https://user-images.githubusercontent.com/32617562/196172362-08d7274d-c663-46ed-a2fd-ed8194bdf489.png)
![image](https://user-images.githubusercontent.com/32617562/196172427-30ecd4e9-3ab2-4c78-a54d-085a023a6a49.png)

**Comment by YukisCoffee** [comment]
Fixed in d1c8a083f09046a1c0d029285a75798cd8f45c9b.

This was formally removed without notice when shelves home was migrated to use WEB v2, perhaps to avoid confusion. I reimplemented the feature with renaming. The new config property used is `useGridHomeStyle`, which is automatically set if the legacy alias `useWebV2HomeEndpoint` is set.

Sorry for removing said feature without public notice or acknowledgement of the alternative userbase...
