### ISSUE TITLE
Age restriction bypass is working weirdly for me

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#122]
So I have the simple age restriction bypass userscript with tampermonkey and when I go to this age restricted video for example: https://www.youtube.com/watch?v=OLLvk8WUGmI I firstly get this error:
**Warning: Attempt to read property "text" on null in D:\xampp\htdocs\models\Watch\Watch8\MVideoPrimaryInfoRenderer.php on line 378** 
The video does seem to load however but I have to manually delete the **player-unavailable** element. I'm not sure if this is just a me issue so I decided to create an issue just incase

**Comment by YukisCoffee** [comment]
Null share button fixed by 3487c515f5da5b3852171a47a340816596e51af7.

However, compatibility with many userscripts is not within the scope of the project and cannot be reasonably considered; after all, **they are designed for completely different engines.** Due to the usefulness of this particular one, an exemption has been made, however **support will not be provided** beyond the most basic functionality (which it does provide).

There is indeed a check to remove the screen if Rehike can detect the script's presence, however this has only been tested with the extension version and it's not guaranteed to work the same on the userscript version.

I recommend using a userstyle to hide `#player-unavailable` instead, or modifying the SYARB userscript to detect and remove the hitchhiker element.

**Comment by randomperson189** [comment]
alright I'll do that, thanks for the info
