### ISSUE TITLE
rehike without proxying

### ISSUE THREAD

**Issue by Naleksuh** [Rehike/Rehike#130]
Is there any reason why proxying youtube.com/fiddling with root certs/etc is *required* for Rehike? While you would need that for youtube.com to show Rehike, why can't Rehike simply support the software working at a different URL? And if it already does, why do the instructions say otherwise?

**Comment by aubymori** [comment]
Hi, we use a proxy to funnel Rehike onto YouTube's domain because of CORS, which makes it so that the player can't play videos on other domains. We also rely on YouTube cookies for signing in, which means you can't sign in on other domains. There's also an odd bug that we have no idea why it happens, where comments will not load on smooth SPF navigation from one page to another. I hope this explains well enough why we use a proxy as opposed to hosting it on a different domain.
