### ISSUE TITLE
Fatal error on visiting homepage

### ISSUE THREAD

**Issue by Felting** [Rehike/Rehike#143]
After installing rehike into htdocs on xampp mac this page appears.
![image](https://user-images.githubusercontent.com/92234562/200154469-a05824c1-a33a-47f1-a9ed-ed62ad2ad198.png)

**Comment by YukisCoffee** [comment]
Could you try to run `chmod -R 777 /Applications/XAMPP/xamppfiles/htdocs` and try again? This seems to be a macOS-specific permissions bug, not allowing the PHP server to write to its own source directory (which Rehike needs to be able to for user configuration and cache).

This is my current guess because `fwrite()` takes the response of `fopen()`, which will return a stream (what is needed) upon success and a boolean (what you have) upon an error.

**Comment by Felting** [comment]
It works but has a 404 error on every page.

**Comment by jshayya84** [comment]
Same thing happens with me, but even after running the command, I just get a different error, but I can see some part of YouTube.
![Screen Shot 2022-11-08 at 1 48 47 PM](https://user-images.githubusercontent.com/117734022/200556605-5869a86b-b3e6-481a-bbb1-d05d8dfb4149.png)
![Screen Shot 2022-11-08 at 1 48 51 PM](https://user-images.githubusercontent.com/117734022/200556699-f30bd771-1cca-4913-975d-d357859625c8.png)

**Comment by aubymori** [comment]
what php versionn are you using?

**Comment by toiletflusher** [comment]
Have the same bug except the homepage works but every page doesn't. I am running Debian 11, PHP 7.4.

**Comment by Nightlinbit** [comment]
> Have the same bug except the homepage works but every page doesn't. I am running Debian 11, PHP 7.4.

Use PHP 8.

**Comment by jshayya84** [comment]
> what php version are you using?

PHP 8
