### ISSUE TITLE
Like count not showing up when using Polish i18n (bug)

### ISSUE THREAD

**Issue by PANMARSAG14** [Rehike/Rehike#151]
![chrome_c4Z9X5htWl](https://user-images.githubusercontent.com/81510862/200399139-f0038ec0-4355-46bf-b842-b067029c260d.png)

**Comment by aubymori** [comment]
This is a problem not with the primary video info model, or the like count extractor, but rather the Polish `likeCountIsolator` regex. If you didn't know, it grabs the like count from the unliked accessibility string, which in English, is "like this video along with %s other people". This'll show up in the `aria-label` attribute of the `button` element of the unliked like button in Polymer, which is shown below.
![image](https://user-images.githubusercontent.com/44238627/200421361-f2142a7b-eb32-4700-8090-718c1067df7a.png)

Also, are you manually activating Polish i18n or something? Because there's no official way to switch language, lol.

**Comment by YukisCoffee** [comment]
Yeah, this is something you'll have to resolve on your own to the best of your ability. We currently aren't supporting i18n in any meaningful manner.

**Comment by aubymori** [comment]
> Yeah, this is something you'll have to resolve on your own to the best of your ability. We currently aren't supporting i18n in any meaningful manner.

Yes, I even removed the pickers from the footer, because of i18n not beings upported. However, they will be added back once i18n is a thing.
