### ISSUE TITLE
Mitmproxy not redirecting traffic

### ISSUE THREAD

**Issue by Felting** [Rehike/Rehike#197]
When starting mitmproxy (on linux) to redirect traffic to localhost, nothing happens except a terminal windows like this: 
![image](https://user-images.githubusercontent.com/92234562/204083913-085ca93f-b3ca-4d3d-a1cc-070de07b6075.png)
But all traffic still goes to youtube.com.

**Comment by BowDown097** [comment]
Did you change the proxy port in your browser to 8080?

**Comment by Felting** [comment]
> Did you change the proxy port in your browser to 8080?

How?

**Comment by BowDown097** [comment]
Depends what browser you use. In Firefox, you go into the network settings, then "Manual proxy configuration", then under "HTTP Proxy" put 127.0.0.1 as the IP and 8080 as the port and apply it to HTTPS as well. I imagine the process is familiar for other browsers, but Firefox is the only browser I use.
This should work assuming you haven't done anything to change the port that mitmproxy listens on since the default is 8080.

**Comment by Felting** [comment]
> Depends what browser you use. In Firefox, you go into the network settings, then "Manual proxy configuration", then under "HTTP Proxy" put 127.0.0.1 as the IP and 8080 as the port and apply it to HTTPS as well. I imagine the process is similar for other browsers, but Firefox is the only browser I use. This should work assuming you haven't done anything to change the port that mitmproxy listens on since the default is 8080.

Now it says "Software is Preventing Firefox From Safely Connecting to This Site

www.youtube.com is most likely a safe site, but a secure connection could not be established. This issue is caused by mitmproxy, which is either software on your computer or your network."

**Comment by Felting** [comment]
Nvm fixed it by adding mitmproxy certificate https://stackoverflow.com/questions/62261786/how-to-allow-firefox-to-connect-to-webpage-through-mitmproxy
