### ISSUE TITLE
Make Rehike show that I'm signed in

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#21]
It seems that on the current master branch of Rehike, it thinks that I'm signed out. However the exp-signin-rework branch of this does show that I'm signed in because it shows my profile picture in the top right corner and the notifications bell. Video recommendations based on my account also work on that branch.

This could be an easy fix since I think it has something to do with cookies.

**Comment by YukisCoffee** [comment]
`exp-signin-rework` is currently in development (and is actually on hold until further structural reworkings are complete). `master` branch currently lacks any code related to logging in at all.

This will be fixed in the future as `exp-signin-rework` becomes stable enough to get merged with `master`.

**Comment by randomperson189** [comment]
Alright, all is good. I made my own fork that adds the new features of the master branch to the exp-signin-rework one.

**Comment by YukisCoffee** [comment]
Completely resolved even on `master` now, by 3a0f23343b1fccba907e1f749a18d561a2d7e5e4.

Closing...
