### ISSUE TITLE
[exp-signin-rework] type_error:SafeHtml upon changing comment sort

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#24]
When attempting to change the comment sort, this happens.
![image](https://user-images.githubusercontent.com/44238627/178025221-19c350ec-d615-46dc-873e-b4edb7c193f6.png)
It happens both signed in and out. I've tested, and this does not happen on `new-mvc`.

**Comment by YukisCoffee** [comment]
Also fixed by 8aad03760a6bdb3aee3ad84589127d293e3a41ca.

More specifically, you broke all of `comments_service_ajax` with one little typo here. 
![image](https://user-images.githubusercontent.com/99076687/178208150-cd74b933-7ec7-464c-b77f-bd92075d41bd.png)

`=` in an `if` expression still modifies the variable. Sometimes this is useful, but typos can be hard to trace down. 

That's why I put literals on the left hand side. `if ($a = 30)` won't syntax error, but `if (30 = $a)` will.

Closing...
