### ISSUE TITLE
Vagueness on mitmproxy installation

### ISSUE THREAD

**Issue by mamarkrk** [Rehike/Rehike#262]
I'd like to know what "setting up a script" does

And how to set one up.

**Comment by YukisCoffee** [comment]
Sorry for the vagueness.

mitmproxy uses Python scripts in order to work. Making a script just means saving that to a file with any name and running the below command in the installation instructions with the name in place of the placeholder displayed.

By setting up a script, we just meant creating a file with contents like the one provided.

**Comment by mamarkrk** [comment]
ohh, thanks for the info
