### ISSUE TITLE
Error when going to youtube.com signed in

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#276]
### Rehike version

0.7

### Operating system

Windows 10

### PHP version

8.1

### What's going on?

Whenever I go to youtube.com when signed in, I just get this error

> Unhandled Promise(YukisCoffee\CoffeeRequest\Promise) in D:\xampp\htdocs\modules\Rehike\Signin\AuthManager.php:224
> Stack trace:
> #0 D:\xampp\htdocs\modules\Rehike\Signin\AuthManager.php(224): then(Object(Closure))
> #1 D:\xampp\htdocs\modules\Rehike\Signin\AuthManager.php(190): requestSigninData()
> #2 D:\xampp\htdocs\modules\Rehike\Signin\AuthManager.php(96): getSigninData()
> #3 D:\xampp\htdocs\modules\Rehike\Boot\YtStateManager.php(40): use(Object(Rehike\YtApp))
> #4 D:\xampp\htdocs\modules\Rehike\Boot\YtStateManager.php(27): bindToEverything(Object(Rehike\YtApp))
> #5 D:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(33): init()
> #6 D:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(21): boot()
> #7 D:\xampp\htdocs\index.php(61): startSession()
> #8 {main}
> 
> 
> Full trace:
> #0 D:\xampp\htdocs\modules\YukisCoffee\CoffeeRequest\Promise.php(192): __construct()
> #1 D:\xampp\htdocs\modules\Rehike\Signin\AuthManager.php(224): then(Object(Closure))
> #2 D:\xampp\htdocs\modules\Rehike\Signin\AuthManager.php(190): requestSigninData()
> #3 D:\xampp\htdocs\modules\Rehike\Signin\AuthManager.php(96): getSigninData()
> #4 D:\xampp\htdocs\modules\Rehike\Boot\YtStateManager.php(40): use(Object(Rehike\YtApp))
> #5 D:\xampp\htdocs\modules\Rehike\Boot\YtStateManager.php(27): bindToEverything(Object(Rehike\YtApp))
> #6 D:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(33): init()
> #7 D:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(21): boot()
> #8 D:\xampp\htdocs\index.php(61): startSession()
> #9 {main}
> <br />
> <b>Fatal error</b>:  Uncaught 
>   thrown in <b>D:\xampp\htdocs\modules\YukisCoffee\CoffeeRequest\Util\PromiseResolutionTracker.php</b> on line <b>93</b><br />

**Comment by YukisCoffee** [comment]
Fixed in 2594bce.

I forgot to make the "unresolved promise" error that we use for debugging (it catches simple-to-make mistakes in code that would otherwise be very hard to find) compatible with the ability to chain promises. This means that when you have code that has a `$promise->then()->then()` pattern, as in the sign in request code, it will fail as, although it redirects the second call to act on the response of the first, it still re-registers the first as pending and causes the code to fail.

Closing...
