### ISSUE TITLE
Channel Switching Bug

### ISSUE THREAD

**Issue by Xammand** [Rehike/Rehike#291]
### Rehike version

0.5

### Operating system

Windows 10 Home Version 21H2

### PHP version

8.2.0

### What's going on?

I noticed when I tried switching channels from one to another I saw that the channel I switched to had the same subscriptions and reccomendations the other channel had, I also noticed that the my channel tab took me to the other channel's page. The only thing that changed was the channel icon in the header, which changed to the channel I switched to. I find out if I just log out and log back into the channel I was on, everything would get fixed.

**Comment by YukisCoffee** [comment]
I believe this issue is being worked on in private by a friend who is rewriting the sign in system currently, so Aubrey and I haven't focused on it much.

I wonder, can you work around this issue by deleting the signin cache (should be in `C:\xampp\htdocs\cache` or so, wherever you cloned Rehike to)? I think the channel icon in the header is cached and managed by Rehike's code, but the guide menu and recommendations are handled on the fly and downloaded from YouTube's servers at request time. This sounds to me like it is updating the cache, but incorrectly, such that it continues to authenticate requests for the initial account. Assuming it's not worse (Rehike blocking the signup update procedure from changing your authentication cookies), this should just make it request the data from YouTube again and rebuild its cache.

Assuming that works, we don't offer a way to disable the cache at the moment, though I can ask my friend to include that in the rewrite she's working on, so you will have to do that every time you wish to switch accounts. Perhaps we can release an update to patch this behaviour in the existing system if it is a simple enough bug.

**Comment by tomgram** [comment]
the channel switcher works for me

**Comment by YukisCoffee** [comment]
Should be fixed in 3ae4bc6.

Closing...
