### ISSUE TITLE
yt-dlp isnt working

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [Rehike/Rehike#321]
### Rehike version

0.7

### Operating system

Windows 10

### PHP version

8.0

### What's going on?

doesnt work even with --no-check-certificates argument

**Comment by syndiate** [comment]
Yeah, because the hosts method redirects all network traffic to youtube.com on the computer to the local webserver.

If you're running this while Rehike isn't running, you need to manually go to the hosts file and remove the line with youtube.com in it.

**Comment by ephemeralViolette** [comment]
I think that there just isn't anything we can do about this and the issue should be closed. @aubymori @YukisCoffee, thoughts?

As one last try, the correct spelling of the argument seems to be `--no-check-certificate` (singular, not plural), as I see in references to it in a Google Search. Try using that and let us know if it works out!

**Comment by aubymori** [comment]
> I think that there just isn't anything we can do about this and the issue should be closed. @aubymori @YukisCoffee, thoughts?
> 
> As one last try, the correct spelling of the argument seems to be `--no-check-certificate` (singular, not plural), as I see in references to it in a Google Search. Try using that and let us know if it works out!

It can be either `--no-check-certificates` or `--no-check-certificate`, it doesn't matter.

**Comment by YukisCoffee** [comment]
I tried to replicate this with the latest version of yt-dlp (2023.07.06) on Windows 10, and it seems to work just fine. The only issue that occurs is that it says:

```
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
```

This only occurs because it's downloading the Rehike document, which doesn't contain this variable, hence it refetches the link for InnerTube. Out of curiosity, did you copy/paste a video URL either from search or that has a playlist? The "&" symbol that would be used in these URLs for parameters will cause the command in Windows's command interpreter to be split into two basically, so you will get SSL errors for the video link and then run a non-existent command with the `--no-check-certificate(s)` argument.

**Comment by ephemeralViolette** [comment]
inactive.
