### ISSUE TITLE
I get "No connection" error

### ISSUE THREAD

**Issue by asfasdfasdfsdsdf** [Rehike/Rehike#344]
### Rehike version

0.7

### Operating system

Windows 10

### PHP version

8.2.4

### What's going on?

So i installed all SSL and all of this but, the problem that i did everything in fiddler, i have only firefox open, but in result i get the error when it fixes when i turn off fiddler or xampp, what a miserable error, 
![Screenshot 2023-09-09 at 13-17-40 YouTube](https://github.com/Rehike/Rehike/assets/106913603/803dafd5-9fb3-4f87-90a1-ef0c58bf1a7d)

**Comment by iamatsomeone** [comment]
did you put the repo's root in `C:\xampp\htdocs`?

**Comment by asfasdfasdfsdsdf** [comment]
yes

**Comment by YukisCoffee** [comment]
Hi there. You cannot turn off XAMPP while Rehike is active, or you will have issues with connecting to YouTube.

In this case, YouTube has cached a result of the official frontend loader page, and also Rehike is not successfully loading. If you press Ctrl+Shift+R, then you should reload the page while dropping the case. This will probably lead you to the true error screen, which will likely tell you that it's an unsecure connection.

The SSL setup (that I assumed you performed, on Apache and browser ends) only applies to using hosts file to redirect YouTube. Since you are using Fiddler, you will need to install the Fiddler certificates into your browser.

**Comment by ephemeralViolette** [comment]
inactive
