### ISSUE TITLE
Comments & Sidebar won't load in certain videos.

### ISSUE THREAD

**Issue by kwan-vini** [Rehike/Rehike#347]
### Rehike version

0.7

### Operating system

Windows 10 Pro

### PHP version

8.2.4

### What's going on?

![image](https://github.com/Rehike/Rehike/assets/118130060/9809e28a-ebaa-4441-bb33-2b8e7d97b808)

I don't certainly know what triggers this bug, but it looks like it happens on "less popular videos", with a small number of views, comments, etc...

**Comment by YukisCoffee** [comment]
Hello.

This is not a Rehike issue, but a uBlock Origin issue (that happened to coincide with a similar recent YouTube update haha).

You must turn off the built-in privacy filter in uBO settings, and then Rehike should work fine again. I reckon it's possible to downgrade this list too, but I am not sure how.
![image](https://github.com/Rehike/Rehike/assets/99076687/40f34556-fe85-4d51-95eb-63028e95401a)

**Comment by YukisCoffee** [comment]
The issue has been fixed in a recent commit to uBlock Origin: https://github.com/gorhill/uBlock/commit/ce959164bb3571dd7f9c8a40236c20dae3775153. It's fully a bug uBO introduced with a new scriptlet.

This should be released as an update on web stores soon, but until then, you must manually block a certain scriptlet or disable uBlock Origin altogether. If you wish to keep uBO on, then add these filters manually:

```
! REHIKE FIXES
youtube.com,youtubekids.com,youtube-nocookie.com#@#+js(json-prune-xhr-response, [].playerResponse.adPlacements [].playerResponse.playerAds [].playerResponse.adSlots playerResponse.adPlacements playerResponse.playerAds playerResponse.adSlots adPlacements playerAds adSlots)
```
