### ISSUE TITLE
Privacy error (probably HSTS-related)

### ISSUE THREAD

**Issue by nulcow** [Rehike/Rehike#458]
### Rehike version

0.8.0

### Operating system

Windows 10 1809 (Build 17763.316)

### PHP version

Unavailable, latest version included with XAMPP v3.3.0?

### What's going on?

I have installed and configured XAMPP, placed Rehike in the htdocs directory, set up a redirect in the hosts file, and installed both client and server certificates. I also tried deleting the HSTS data for youtube.com and restarting my computer, but that did not work. I get this page in Vivaldi when trying to access youtube.com, localhost, or 127.0.0.1:
![rehike_issue_certerror](https://github.com/Rehike/Rehike/assets/88356560/3309349c-b43d-4c0c-b78e-f0462fed281e)

This is the certificate information for youtube.com:
![rehike_issue_certinfo](https://github.com/Rehike/Rehike/assets/88356560/0f3fa058-6af4-4172-9388-64387dc25eb1)

I also tried in Internet Explorer to make sure this issue was not exclusive to Vivaldi; here's the result of that:
![rehike_issue_errorie](https://github.com/Rehike/Rehike/assets/88356560/40365c60-61f4-4af7-b6cd-78de47ac9432)

I followed all the instructions precisely, and I did the exact same things as I did last time (except installing Fiddler, because I ended up not using it last time). What is going wrong here?

**Comment by ephemeralViolette** [comment]
Try importing the certificate into the Windows store rather than the browser and then restart the browser. I just installed Vivaldi to test and Rehike loaded successfully taking the certificate from there.

Also, the certificate is only valid for **www**\.youtube\.com. `https://youtube.com` still works since it's a different subdomain that just redirects to the www subdomain, but `https://127.0.0.1` or `https://localhost` will not work because the certificate isn't signed for them.

I assume you also put the subdomain in the hosts file as `127.0.0.1 youtube.com` rather than `127.0.0.1 www.youtube.com` because it's not redirecting you.

**Comment by nulcow** [comment]
> I assume you also put the subdomain in the hosts file as 127.0.0.1 youtube.com rather than 127.0.0.1 www.youtube.com because it's not redirecting you.

Really? When I comment the line `127.0.0.1 youtube.com` out of my hosts file it shows the regular YouTube website. And I did import the certificate in both Windows and Vivaldi. Either way, I'll try different domain names and see if it works.

**Comment by nulcow** [comment]
UPDATE: When changing the line `127.0.0.1 youtube.com` to `127.0.0.1 www.youtube.com', it works again.
