### ISSUE TITLE
Player CSS doesn't load randomly

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#46]
This seems entirely random, and a quick refresh seems to fix it most of the time.

**Comment by YukisCoffee** [comment]
Seems to be fixed now?

I don't even know, but there's not much point in keeping this issue open any longer anyways. It's too vague in the first place to be of much use.

**Comment by aubymori** [comment]
this still happens to me

**Comment by YukisCoffee** [comment]
On the other hand, I have never been able to reproduce this bug in the months since this issue was posted. It's likely that this is a browser-specific issue, as the player loading mechanism is not too dissimilar from Polymer's own, and the CSS is downloaded directly from YouTube's servers.

Perhaps a caching issue?
