### ISSUE TITLE
'Uploaded on' string for videos uploaded before August or July 2011

### ISSUE THREAD

**Issue by VexorionReal** [Rehike/Rehike#473]
### Describe the feature

In the original Hitchhiker, there were two strings before the video upload date: 'Published on' and 'Uploaded on'. 'Uploaded on' was used for videos uploaded before August or July 2011, while 'Published on' was used for videos uploaded in August 2011 or later. Would it be possible to implement something like this for Rehike? V3 has this too.

**Comment by aubymori** [comment]
"Uploaded on" applies to non-public videos, not videos before a certain date. Rehike already does this. Look at any archive of old videos like Me at the zoo or Never Gonna Give You Up and you will see that it says "Published on".

**Comment by VexorionReal** [comment]
Right.

**Comment by ephemeralViolette** [comment]
In fact, "uploaded on" still displays on videos uploaded today, but only if they were never publicised. There's no way to detect if a video has been public in the past with the desktop Polymer API, so we just assume that any non-public video has never been public. So the way Rehike displays it is wrong if the video was uploaded as public and then set to unlisted/private, or uploaded as non-public, set to public, and then set back to non-public.

Publicising a video for the first time also changes the date in the watch page altogether to the date that it was made public, rather than the date that it was uploaded. You can still view the original upload date in YouTube Studio, but the date of publication takes precedent for the information InnerTube responds with.
