### ISSUE TITLE
CoffeeTranslation performance issues

### ISSUE THREAD

**Issue by TorutheRedFox** [Rehike/Rehike#518]
### Rehike version

0.8.0

### Operating system

Windows NT 10.0 (Windows 10 22H2)

### PHP version

8.3.2

### What's going on?

After looking around a cachegrind output by Xdebug, CoffeeTranslation takes up a sizable chunk of the time spent by PHP on responding to the request. Optimizing it should reduce a sizable chunk of the load time.

**Comment by YukisCoffee** [comment]
Fixed in f99cc57.

This is because the cache implementation was botched, so nothing was being added to the cache list. When performing a lookup, we would go and search for the cache entries in memory, but since they didn't exist, it just loaded the file again and again.

Now the biggest things taking up execution time seem to network requests and Google's protobuf library.
