### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by bluedragon-cairo** [Rehike/Rehike#529]
### Rehike version

0.8.0

### Operating system

Windows Server 2019

### PHP version

latest

### What's going on?

I'm trying to make Korean language, and I changed misc.i18n file that has texts for the subscribe button and views text. However the view count ("views") still display in English, and the subscribe button shows the translated text only if I'm logged out. If I'm logged in the English text is viewed. (Using the master branch)

**Comment by YukisCoffee** [comment]
Did you make sure to change the locale name in `_rhcfg.json` to the proper InnerTube language ID for Korean (`ko`)?

Otherwise, I think that a regex may be malformed.

It would be helpful if you could publish whatever work you have so far so we could test.

**Comment by YukisCoffee** [comment]
It's not immediately obvious, but `viewTextSingular` and `viewTextPlural` are only used whenever Rehike needs to recreate these strings on its own. Otherwise we just get them from the InnerTube API, and I think this is also true for the signed in subscribe button.

So I'm assuming that the most likely scenario is that InnerTube isn't using Korean language, either because you did not set `ko` language code in the configuration or because it was another code, which would likely be malformed input.

**Comment by bluedragon-cairo** [comment]
I first just modified the strings in en-US and later I created ko-KR directory and changed the language in config.json, but didn't know about _rhcfg.json. I'll try changing _rhcfg.json too.

**Comment by bluedragon-cairo** [comment]
Oh ok. Changing _rhcfg.json did the thing. I'll push request the Korean language files just in case.

**Comment by bluedragon-cairo** [comment]
Now another issue happens, the subscriber cound next to the subscribe button shows as "X subscribers" instead of just the count itself, seems to be innertube issue though

**Comment by YukisCoffee** [comment]
> Now another issue happens, the subscriber cound next to the subscribe button shows as "X subscribers" instead of just the count itself, seems to be innertube issue though

This is an issue with your regular expression. The count needs to be isolated from the surrounding text.

**Comment by YukisCoffee** [comment]
Specifically, `subscriberCountIsolator` in `regex.i18n` file.

**Comment by bluedragon-cairo** [comment]
Thanks
