### ISSUE TITLE
Issue i had from Attempt 2 of installing Rehike.

### ISSUE THREAD

**Issue by sulflix** [Rehike/Rehike#536]
I posted my entire journey on installing on the rehike server at the #support channel.
![image](https://github.com/Rehike/Rehike/assets/84033342/d135cd62-0b0d-46de-a549-1b1900873696)
All 3 buttons still give me the same error.

**Comment by sulflix** [comment]
![image](https://github.com/Rehike/Rehike/assets/84033342/3cb71957-470f-41e0-bf6b-2901f7dcaf03)
![image](https://github.com/Rehike/Rehike/assets/84033342/70f383df-5ed0-425f-a746-861390c5cba5)
Versions of the OS and Browser i use.

**Comment by DavidCGranger** [comment]
Read the guide...
This problem occurs if you didn't set permissions for the folder correctly on Linux or Mac...

-------- Original Message --------

**Comment by sulflix** [comment]
I read the guide from the mac-OS focused page.

**Comment by DavidCGranger** [comment]
The wiki says the following:

"⚠️ Problem notice!! ⚠️ - macOS/Linux FS errors

On macOS and Linux, Rehike may crash at startup, and you will see the Rehike Fatal Error screen. This is because Rehike cannot write the configuration or cache files into its install directory.

If you get any error relating to files, run chmod -R 777

where

is your XAMPP htdocs directory. This is /Applications/XAMPP/xamppfiles/htdocs and /opt/lampp/htdocs on macOS and Linux by default, respectively."

-------- Original Message --------
