### ISSUE TITLE
Randomly got this error for no reason

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#542]
I was using youtube with rehike watching a livestream until it just randomly broke for no reason, tried refreshing the page several times and turning xampp off and on but it didn't work, restarting my pc seemed to fix it
![image](https://github.com/Rehike/Rehike/assets/32617562/d880769e-5a30-4b76-8304-e8d6085b8a7d)

**Comment by kawapure** [comment]
There's not much that we can say about this issue, because it simply seems that your PC began to fail at looking up DNS records (the actual www.youtube.com IP address). This probably occurred as a result of a network outage, but presumably only Rehike was affected (although we don't cache the DNS lookup result at all).

This particular error was not meant to happen though, and has been fixed since https://github.com/Rehike/Rehike/commit/bb6ce3e090c5e103212ec0387afe0f5fe9c745d5. You would still get an error, but not a PHP compiler error, and you should get more information in that case.
