### ISSUE TITLE
Unknown DnsLookupException after OS update

### ISSUE THREAD

**Issue by RealPortalPlayer** [Rehike/Rehike#582]
### Rehike version

0.8.1

### Operating system

Arch-Linux 6.9.5-arch1-1

### PHP version

8.2.12

### What's going on?

I updated my system, and now Rehike doesn't want to work at all.

``````Uncaught Error: Typed static property Rehike\ConfigManager\Config::$config must not be accessed before initialization in /opt/lampp/htdocs/modules/Rehike/ConfigManager/Config.php:168 Stack trace: #0 /opt/lampp/htdocs/modules/Rehike/Logging/LogFile.php(70): Rehike\ConfigManager\Config::getConfig() #1 /opt/lampp/htdocs/modules/Rehike/Logging/LogFileManager.php(43): Rehike\Logging\LogFile->render() #2 /opt/lampp/htdocs/modules/Rehike/Logging/LogFileManager.php(34): Rehike\Logging\LogFileManager::writeLogFile(Object(Rehike\Logging\LogFile)) #3 /opt/lampp/htdocs/modules/Rehike/ErrorHandler/ErrorHandler.php(113): Rehike\Logging\LogFileManager::createExceptionLogFile(Object(Rehike\Logging\Common\FormattedString)) #4 [internal function]: Rehike\ErrorHandler\ErrorHandler::handleUncaughtException(Object(Rehike\Util\Nameserver\DnsLookupException)) #5 {main} thrown``````

I tried reinstalling Rehike, but the problem persists.

It references `Rehike\Util\Nameserver\DnsLookupException`, but I can access new YouTube perfectly fine

**Comment by kawapure** [comment]
Please note that the above commit that I created only fixes bugs related to the obfuscation of the main bug.

DnsLookupException is indeed the true issue here, and it has not been fixed.

> but I can access new YouTube perfectly fine

Is this with the Rehike server enabled (?enable_polymer=1 URL parameter) or by disabling the Rehike server?

Also, feel free to fiddle around in [`/modules/Rehike/Util/Nameserver/Nameserver.php`](//github.com/Rehike/Rehike/tree/master/modules/Rehike/Util/Nameserver/Nameserver.php). It's possible that failure occurs for you with 1.1.1.1 nameserver, so a different one may work better.

**Comment by RealPortalPlayer** [comment]
That does reveal the real error. It fails to get DNS records. I tried changing it to both Google's and Quad9, but neither of them seems to fix that.

Also, [`/modules/Rehike/Boot/Tasks.php`](https://github.com/Rehike/Rehike/blob/master/modules/Rehike/Boot/Tasks.php#L37) seems to have `1.1.1.1` hard-coded. I doubt this is intentional

**Comment by kawapure** [comment]
Please ensure that PHP can access the internet in general. I heard of this issue occurring at random on Windows and being fixed with a restart, but I've never encountered it myself, nor do I know how to debug it on Linux at all.

> Also, [`/modules/Rehike/Boot/Tasks.php`](https://github.com/Rehike/Rehike/blob/master/modules/Rehike/Boot/Tasks.php#L37) seems to have `1.1.1.1` hard-coded. I doubt this is intentional

Seems to be a leftover of the previous architecture, since I believe that the custom nameserver handling was originally going to be a feature of the general CoffeeRequest library before being moved to a Rehike-specific component.

**Comment by RealPortalPlayer** [comment]
PHP can access the internet. Replacing the `index.php` file with
```php
<?php
echo file_get_contents('http://example.com');
```
gets the contents of the example site perfectly fine

My guess is this is an ISP problem, and I just so happen to get it after updating my computer

**Comment by kawapure** [comment]
Perhaps... Here's an example PHP file worth seeing the contents of:

```php
<?php
$ns = [ "1.1.1.1" ];
$cname = dns_get_record("www.youtube.com", DNS_CNAME, $ns);

if (isset($cname[0]["target"]))
{
    $requestUri = $cname[0]["target"];
}
else
{
    echo "Failed to get request URI.";
    die();
}

$ipv4Records = dns_get_record($requestUri, DNS_A, $ns);
$ipv6Records = dns_get_record($requestUri, DNS_AAAA, $ns);

var_dump($ipv4Records);
var_dump($ipv6Records);
```

One theory that I have right now is that only IPv6 is available for you, and that's causing Rehike's code to fail validating the IP address because we only accept IPv4 at the moment, so it rejects the nameserver lookup and throws that exception.

**Comment by RealPortalPlayer** [comment]
I just get `Failed to get request URI.` even if I change `$ns` IP or change the URL to the example site

**Comment by kawapure** [comment]
Odd. Could you add a `var_dump($cname);` after it's set? I'm going to assume it's blank. Now the issue that I speculate is that PHP's DNS functions are broken for some reason.

I'm looking into alternative methods to perform the DNS lookup if this is a persistent issue.

**Comment by RealPortalPlayer** [comment]
It is empty. I guess PHP broke something

**Comment by kawapure** [comment]
Related Stack Overflow question, but no notable replies:
https://stackoverflow.com/questions/30711434/why-does-dns-get-record-php-function-returns-empty-array

Here is an interesting article about the behaviour of `dns_get_record()` on Linux specifically, but it's a few years out of date:
https://dustri.org/b/a-short-tale-on-phps-dns_get_record.html

This article may still have information to help you debug this issue. 

Here's a custom DNS library for PHP that I'm looking into:
https://github.com/bluelibraries/dns

This library can manage DNS requests via manual TCP requests, so it could avoid bugs with PHP's specific implementation. I doubt that there are any issues with PHP's network code as a whole, since you could resolve example.com via file_get_contents() just fine. I'll try to hack together an integration of this method into Rehike for you.

**Comment by kawapure** [comment]
I added support for the aforementioned library here: https://github.com/Rehike/Rehike/commit/3a9a76324f94706c5d38237e4ced8fb163a79e8d

You can give it a try by switching your branch to [582-unknown-dnslookupexception-after-os-update](//github.com/Rehike/Rehike/tree/582-unknown-dnslookupexception-after-os-update). This will avoid the PHP library unless it fails itself, so this should hopefully work for you.

**Comment by RealPortalPlayer** [comment]
Thanks that works perfectly. I'll close this issue, but you're free to re-open it if needed.

**Comment by kawapure** [comment]
I should mention: these changes are now merged into the `master` branch, so you can switch back now.
