### ISSUE TITLE
Rehike Update Error

### ISSUE THREAD

**Issue by Xammand** [Rehike/Rehike#585]
### Rehike version

0.8.1

### Operating system

Windows 10 Home 22H2

### PHP version

8.2.4

### What's going on?

So for the most part, I keep Rehike updated every time I see a new update on the about page and today I checked and there was an update from 4 days ago and that didn't show up yesterday or the day before or the day before that and if I try to update it gives this error: 

**Failed to pull changes from the remote source. Git error log:

fatal: detected dubious ownership in repository at 'C:/xampp/htdocs' 'C:/xampp/htdocs' is owned by: 'S-1-5-32-544' but the current user is: 'S-1-5-21-4281830436-1393969876-4151674489-1001' To add an exception for this directory, call: git config --global --add safe.directory C:/xampp/htdocs**

For some reason, it also says that im on the update that apparently im not on.

![Screenshot_193](https://github.com/Rehike/Rehike/assets/84749558/c4684887-3277-4941-a9b8-58d2a21a7427)
![Screenshot_194](https://github.com/Rehike/Rehike/assets/84749558/45ae5774-ec5a-445c-b1f8-38f7d140dcd2)

**Comment by kawapure** [comment]
I suppose that the update check code doesn't work when you are on a non-master branch. I would just `git checkout master` and `git reset --hard origin/master`, which will force an update. We don't do this because it would delete developer's modified files, but for ordinary users it's fine.

Also, try running that command that the error message mentions. The error message is a little bit vague, but `S-1-32-544` is a well-known SID for the administrators group on Windows, so it just means that the folder is owned by the administrators group, but not your user account (the long SID starting with `S-1-5-21`).

**Comment by Xammand** [comment]
> I suppose that the update check code doesn't work when you are on a non-master branch. I would just `git checkout master` and `git reset --hard origin/master`, which will force an update. We don't do this because it would delete developer's modified files, but for ordinary users it's fine.
> 
> Also, try running that command that the error message mentions. The error message is a little bit vague, but `S-1-32-544` is a well-known SID for the administrators group on Windows, so it just means that the folder is owned by the administrators group, but not your user account (the long SID starting with `S-1-5-21`).

I put in that code the error had and it fixed itself, I was able to update and now it's all good. Closing.
