### ISSUE TITLE
Introduce system for user-submitted modifications (Nepeta)

### ISSUE THREAD

**Issue by kawapure** [Rehike/Rehike#590]
Nepeta is a work-in-progress modding to allow users to create their own extensions to Rehike. The base release will cover the following:

- Running custom PHP scripts
- Replacing page controllers in CV2
- Custom page templates

Future releases may cover the following topics:

- IPC and multiple PHP servers
- Support for application logic in native code via FFI
- Marshalling PHP objects for consumption over IPC and FFI (i.e. in a COM-like style)

There is existing work for Nepeta by Taniko already, but it's heavily unfinished and does not focus on the priority goals for 1.0, instead focusing on experimental features like IPC and whatnot.

**Comment by YukisCoffee** [comment]
Comments on Nepeta IPC: it was always purely an experiment.

Synchronizing multiple PHP processes is extremely difficult, and the more I've thought about it in the months I've been planning Nepeta, it's seemed more and more insane to even attempt. Aside from the issues inherit to spawning multiple processes like the absurd weight of processes in NT compared to Unix-likes, we also don't really have any good communication mechanisms.

The "message port" would work decently, but it would require both the client and the server to be in a specific state in order for one to work. In the best possible design without Isabella's scheduler experiment, messaging would be a state that the server (with all of its responsibilities) only enters a couple times during its lifetime, whereas the client would stay alive in the message loop for most of its lifetime. Hence, you get a huge synchronization issue which destroys any benefit of IPC: the client can wait for several seconds for the server to finally enter the message loop one of the few set times that it would in order to access server memory.

There is no mechanism to send an interrupt from one end to the other, nor is it possible to directly share memory like what's possible in native code.

The aforementioned scheduler experiment would improve client-server communications drastically, however I still don't think that it would be good enough. Scheduling would introduce useful "interrupts" into the PHP bytecode, which would allow the server to check by the message port much more frequently. This could realistically emulate multithreading, although I wonder at what expense... Memory access would be much slower over the message port than directly in the same process, such that I imagine that any performance benefits from asynchronous access would be nil.

However, my original idea for Nepeta IPC was to 1.) enforce API stability by making everything have to be marshalled, and 2.) have a sandboxed environment for mods to run in so that they couldn't muddy the state of Rehike code directly. This was an overly convoluted synchronous design. It only later was reimagined to emulate multithreading in some crude form.

As for FFI support and Nepeta COM, I think that these are insane and should not be focused on. An extensions system like Nepeta just needs to be able to load arbitrary user code and maybe modify some of the existing code of Rehike. We should just keep things simple and close to the existing architecture of Rehike. I think that Nepeta could benefit from API redirection in order to maintain API stability, but that's basically all that's needed.

**Comment by kawapure** [comment]
@YukisCoffee I agree. We would certainly benefit more from leveraging a multithreading extension (do any exist for PHP 8.x which are compatible with both *nixes and Windows?) than this strange multiple processes approach. The use thereof, if implemented well, could benefit the performance of the Rehike core on top of providing functionality to mods.

Such a critical feature shouldn't be encapsulated into the Nepeta project, in my opinion.
