### ISSUE TITLE
Request: ChatReplay Integration

### ISSUE THREAD

**Issue by Syreyup** [Rehike/Rehike#640]
### Describe the feature

This may be too far out of your scope, but id like to request it anyway just in case. I personally use the [ChatReplay](https://chatreplay.stream/) extension often to view the replay of twitch chat on streamers vods. It's an opt in/request system, so not a lot of people use it. But one example is Vinesauce. Unfortunately, this doesn't work with rehike, other than a popout window, and is a bit annoying. Not detrimental, but a bit annoying lol

![msedge_SqgQXu4R3r](https://github.com/user-attachments/assets/a9f20a05-5c25-440a-80dc-6bb5962d81e7)

again, nothing against you if you choose to ignore or remove this request, again, not made by you so its not your problem, but i wanted to put this somewhere, and maybe someone can see this and make it themselves through a branch or something, idk how this works fully lmao, sorry

take care, thanks for reading

**Comment by kawapure** [comment]
Fixing up extensions to inject into the older HTML that the Rehike server responds with would usually require forking the extension. In other words, this problem is on part of the extension, and likely can't be solved within Rehike's codebase without dirty hacks. The extension would most likely look for a specific element name on the page to see where it should inject the chat view, and our names have to all differ from what modern YouTube provides.

Since the script doesn't appear to be open source, I don't know how to proceed with such measures.

**Comment by Syreyup** [comment]
all good! thanks for being blunt with me lol usually people just go "well maybe" but you're straight to the point!

take care!
